prueba:
    resource: "@pruebaBundle/Controller/"
    type:     annotation
    prefix:   /

acme_blog:
    resource: "@AcmeBlogBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
